- name: catalogue playbook
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable new
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: Add the user roboshop
    ansible.builtin.user:
      name: roboshop
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: Unzip the application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: build the app with dependencies and in app directory
    ansible.builtin.command: npm install
    args:
     chdir: /app
  - name: copy catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: daemon_reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes     
  - name: copy mongodbrepo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongo client
    ansible.builtin.package:
      name:  mongodb-org-shell
      state: present
  - name: get the categories count 
    ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count
  - name: load catalogue to database
    ansible.builtin.command: mongo --host mongodb.jhansidevops.icu </app/schema/catalogue.js
    when: product_count.stdout == "0"
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes


  

  