- name: mysql
  hosts: mysql
  become: yes
  vars:
   password: RoboShop@1
  tasks: 
  - name: disable mysql
    ansible.builtin.command: dnf module disable mysql -y
  
  - name: copy mysqlrepo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: giving password to db and initializing
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 